SELECT  T0."ART1_ID"
T0."ROUND_TYPE" 
--1 REDONDEO - 2 NO REDONDEO
FROM "SBO_FIGURETTI_PROD"."BEAS_STL" T0
INNER JOIN "SBO_FIGURETTI_PROD"."OITM" T1 ON T0."ItemCode" = T1."ItemCode"
LEFT JOIN "SBO_FIGURETTI_PROD"."OITM" T2 ON T0."ART1_ID" = T2."ItemCode"
WHERE  T1."validFor" = 'Y' and T1."U_SYP_SUBGRUPO2" = "CARTON"


oitm U_SYP_SUBGRUPO2